ORDER_SHIPPED = [
    {
        "AmazonOrderId": "407-6462826-9892326",
        "BuyerInfo": {"BuyerEmail": "0fqqxc7r722f7fk@marketplace.amazon.fr"},
        "EarliestShipDate": "2024-01-12T22:59:59Z",
        "FulfillmentChannel": "AFN",
        "HasRegulatedItems": False,
        "IsAccessPointOrder": False,
        "IsBusinessOrder": False,
        "IsGlobalExpressEnabled": False,
        "IsISPU": False,
        "IsPremiumOrder": False,
        "IsPrime": False,
        "IsReplacementOrder": "false",
        "IsSoldByAB": False,
        "LastUpdateDate": "2024-01-12T02:48:37Z",
        "LatestShipDate": "2024-01-12T22:59:59Z",
        "MarketplaceId": "A13V1IB3VIYZZH",
        "NumberOfItemsShipped": 2,
        "NumberOfItemsUnshipped": 0,
        "OrderItems": [
            {
                "ASIN": "B0C2B1MJTM",
                "BuyerInfo": {},
                "IsGift": "false",
                "IsTransparency": False,
                "ItemPrice": {"Amount": "95.98", "CurrencyCode": "EUR"},
                "ItemTax": {"Amount": "16.00", "CurrencyCode": "EUR"},
                "OrderItemId": "34813104020682",
                "ProductInfo": {"NumberOfItems": "1"},
                "PromotionDiscount": {"Amount": "0.00", "CurrencyCode": "EUR"},
                "PromotionDiscountTax": {"Amount": "0.00", "CurrencyCode": "EUR"},
                "QuantityOrdered": 2,
                "QuantityShipped": 2,
                "SellerSKU": "FURN_8888",
                "Title": "Clever Elf - Décoration de Table de Noël",
            }
        ],
        "OrderStatus": "Shipped",
        "OrderTotal": {"Amount": "95.98", "CurrencyCode": "EUR"},
        "OrderType": "StandardOrder",
        "PaymentMethod": "Other",
        "PaymentMethodDetails": ["Standard"],
        "PurchaseDate": "2024-01-11T11:01:53Z",
        "SalesChannel": "Amazon.fr",
        "SellerOrderId": "407-6462826-9892326",
        "ShipServiceLevel": "Expedited",
        "ShipmentServiceLevelCategory": "Expedited",
        "ShippingAddress": {
            "City": "Nanterre",
            "CountryCode": "FR",
            "PostalCode": "92000",
        },
    }
]

ORDER_CANCEL = [
    {
        "AmazonOrderId": "171-0934730-2565153",
        "BuyerInfo": {},
        "EarliestShipDate": "2024-01-28T22:59:59Z",
        "FulfillmentChannel": "AFN",
        "HasRegulatedItems": False,
        "IsAccessPointOrder": False,
        "IsBusinessOrder": False,
        "IsGlobalExpressEnabled": False,
        "IsISPU": False,
        "IsPremiumOrder": False,
        "IsPrime": False,
        "IsReplacementOrder": "false",
        "IsSoldByAB": False,
        "LastUpdateDate": "2024-01-30T19:57:43Z",
        "LatestShipDate": "2024-01-28T22:59:59Z",
        "MarketplaceId": "A13V1IB3VIYZZH",
        "NumberOfItemsShipped": 0,
        "NumberOfItemsUnshipped": 0,
        "OrderItems": [
            {
                "ASIN": "B0CJV1B6KB",
                "BuyerInfo": {},
                "IsGift": "false",
                "IsTransparency": False,
                "OrderItemId": "34989299329122",
                "ProductInfo": {"NumberOfItems": "1"},
                "QuantityOrdered": 0,
                "QuantityShipped": 0,
                "SellerSKU": "FURN_9999",
                "Title": "Clever Elf - Guirlande Lumineuse",
            }
        ],
        "OrderStatus": "Canceled",
        "OrderType": "StandardOrder",
        "PaymentMethod": "Other",
        "PaymentMethodDetails": ["Standard"],
        "PurchaseDate": "2024-01-19T09:39:25Z",
        "SalesChannel": "Amazon.fr",
        "SellerOrderId": "171-0934730-2565153",
        "ShipServiceLevel": "Expedited",
        "ShipmentServiceLevelCategory": "Expedited",
    }
]
